FROM node:21-alpine
WORKDIR /app
COPY package.json ./
RUN npm i
COPY . .
CMD ["npx", "ts-node", "./src/index.ts"]
EXPOSE 8000

# BUILD
# docker build . -f Dockerfile.dev -t gateway:dev

# RUN
# docker run -d -p 8000:8000 --name gateway_dev gateway:dev
